# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eebe1a3ba3a448d3147a1f94a8c6392ef69e6c07f5993b49225671545cf87c97baddc584b1341ddd35c4f049af61404d4bc6865dcb04359c89b64d07884f55d8

test:
  secret_key_base: 5ae5d27f6f0ac769398dac2f15ff557b850da5e110c15f165a8c30de4aa1124930ecc9c04d9214d370b736801c0f35f84ec120addcd113592990a994e5f952f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
